#include "vs_native_fast_meta.h"

#include <stddef.h>

static uint8_t meta_nz(SmbNeoNativeContext *ctx, uint8_t value) {
    ctx->status = (uint8_t)((ctx->status & (uint8_t)~(NATIVE_N | NATIVE_Z)) |
        (value & NATIVE_N) | (value == 0u ? NATIVE_Z : 0u));
    return value;
}

static void meta_adc(SmbNeoNativeContext *ctx, uint8_t value) {
    unsigned sum = (unsigned)ctx->a + value +
        ((ctx->status & NATIVE_C) != 0u ? 1u : 0u);
    uint8_t result = (uint8_t)sum;
    ctx->status = (uint8_t)((ctx->status &
        (uint8_t)~(NATIVE_C | NATIVE_V)) |
        (sum > 255u ? NATIVE_C : 0u) |
        ((~(ctx->a ^ value) & (ctx->a ^ result) & 0x80u) != 0u
            ? NATIVE_V : 0u));
    ctx->a = meta_nz(ctx, result);
}

bool vs_native_fast_meta_render_area(SmbNeoNativeContext *ctx) {
    uint8_t *ram;
    const uint8_t *prg;
    uint16_t graphics[4];
    uint8_t attribute_column;
    uint8_t metatile_side;
    uint8_t attribute_row = 0u;
    uint8_t buffer_offset = 0u;

    if (ctx == NULL || ctx->ram == NULL || ctx->prg == NULL)
        return false;
    ram = ctx->ram;
    prg = ctx->prg;
    if (ram[0x0340u] != 0u)
        return false;

    /* Validate all indirect source ranges before mutating state.  The VS
     * cartridge's four metatile tables live in immutable PRG; aliases retain
     * the generated byte-ordered fallback. */
    for (unsigned palette = 0u; palette < 4u; ++palette) {
        graphics[palette] = (uint16_t)(prg[0x0d09u + palette] |
            ((uint16_t)prg[0x0d0du + palette] << 8));
        if (graphics[palette] < 0x8000u ||
            graphics[palette] > 0xff00u)
            return false;
    }

    attribute_column = (uint8_t)(ram[0x0726u] & 1u);
    metatile_side = (uint8_t)(((ram[0x071fu] & 1u) ^ 1u) << 1);
    ram[5] = attribute_column;
    ram[0] = 0u;
    ram[0x0342u] = ram[0x0721u];
    ram[0x0341u] = ram[0x0720u];
    ram[0x0343u] = 0x9au;
    ram[4] = 0u;

    for (uint8_t row = 0u; row < 13u; ++row) {
        uint8_t metatile = ram[0x06a1u + row];
        uint8_t palette = (uint8_t)(metatile >> 6);
        uint8_t tile_offset = (uint8_t)(metatile << 2);
        uint8_t tile_index;
        uint8_t attribute_bits;

        ram[1] = row;
        ram[3] = (uint8_t)(metatile & 0xc0u);
        ram[6] = (uint8_t)graphics[palette];
        ram[7] = (uint8_t)(graphics[palette] >> 8);
        ram[2] = tile_offset;

        ctx->status &= (uint8_t)~NATIVE_C;
        ctx->a = metatile_side;
        meta_adc(ctx, tile_offset);
        tile_index = ctx->a;
        ram[0x0344u + buffer_offset] =
            prg[(graphics[palette] - 0x8000u) + tile_index];
        ram[0x0345u + buffer_offset] =
            prg[(graphics[palette] - 0x8000u) + tile_index + 1u];

        if (attribute_column == 0u)
            attribute_bits = (uint8_t)(palette <<
                ((row & 1u) != 0u ? 4u : 0u));
        else
            attribute_bits = (uint8_t)(palette <<
                ((row & 1u) != 0u ? 6u : 2u));
        ram[3] = attribute_bits;
        ram[0x03f9u + attribute_row] |= attribute_bits;
        if ((row & 1u) != 0u)
            ++attribute_row;
        ram[4] = attribute_row;
        buffer_offset = (uint8_t)(buffer_offset + 2u);
        ram[0] = buffer_offset;
    }

    ctx->x = 13u;
    ctx->y = (uint8_t)(buffer_offset + 3u);
    ram[0x0341u + ctx->y] = 0u;
    ram[0x0340u] = ctx->y;
    ++ram[0x0721u];
    if ((ram[0x0721u] & 0x1fu) == 0u) {
        ram[0x0721u] = 0x80u;
        ram[0x0720u] ^= 4u;
    }

    ctx->status = (uint8_t)((ctx->status |
        NATIVE_C) & (uint8_t)~(NATIVE_N | NATIVE_Z));
    ctx->a = 6u;
    ram[0x0773u] = 6u;
    return true;
}
