#!/usr/bin/env python3
"""Generate desktop RGB and Neo Geo words from one pinned NES palette."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


PALETTE_NAME = "FCEUX 2.2.1 default"
PALETTE_SOURCE = (
    "https://github.com/TASEmulators/fceux/tree/fceux-2.2.1/"
    "src/palettes"
)

# The FCEUX 2.2.1 default table is expressed in the same six-bit component
# values used by its source. See THIRD_PARTY_NOTICES.md for provenance.
FCEUX_221_RGB6 = (
    (0x1D, 0x1D, 0x1D), (0x09, 0x06, 0x23),
    (0x00, 0x00, 0x2A), (0x11, 0x00, 0x27),
    (0x23, 0x00, 0x1D), (0x2A, 0x00, 0x04),
    (0x29, 0x00, 0x00), (0x1F, 0x02, 0x00),
    (0x10, 0x0B, 0x00), (0x00, 0x11, 0x00),
    (0x00, 0x14, 0x00), (0x00, 0x0F, 0x05),
    (0x06, 0x0F, 0x17), (0x00, 0x00, 0x00),
    (0x00, 0x00, 0x00), (0x00, 0x00, 0x00),
    (0x2F, 0x2F, 0x2F), (0x00, 0x1C, 0x3B),
    (0x08, 0x0E, 0x3B), (0x20, 0x00, 0x3C),
    (0x2F, 0x00, 0x2F), (0x39, 0x00, 0x16),
    (0x36, 0x0A, 0x00), (0x32, 0x13, 0x03),
    (0x22, 0x1C, 0x00), (0x00, 0x25, 0x00),
    (0x00, 0x2A, 0x00), (0x00, 0x24, 0x0E),
    (0x00, 0x20, 0x22), (0x00, 0x00, 0x00),
    (0x00, 0x00, 0x00), (0x00, 0x00, 0x00),
    (0x3F, 0x3F, 0x3F), (0x0F, 0x2F, 0x3F),
    (0x17, 0x25, 0x3F), (0x33, 0x22, 0x3F),
    (0x3D, 0x1E, 0x3F), (0x3F, 0x1D, 0x2D),
    (0x3F, 0x1D, 0x18), (0x3F, 0x26, 0x0E),
    (0x3C, 0x2F, 0x0F), (0x20, 0x34, 0x04),
    (0x13, 0x37, 0x12), (0x16, 0x3E, 0x26),
    (0x00, 0x3A, 0x36), (0x1E, 0x1E, 0x1E),
    (0x00, 0x00, 0x00), (0x00, 0x00, 0x00),
    (0x3F, 0x3F, 0x3F), (0x2A, 0x39, 0x3F),
    (0x31, 0x35, 0x3F), (0x35, 0x32, 0x3F),
    (0x3F, 0x31, 0x3F), (0x3F, 0x31, 0x36),
    (0x3F, 0x2F, 0x2C), (0x3F, 0x36, 0x2A),
    (0x3F, 0x39, 0x28), (0x38, 0x3F, 0x28),
    (0x2A, 0x3C, 0x2F), (0x2C, 0x3F, 0x33),
    (0x27, 0x3F, 0x3C), (0x31, 0x31, 0x31),
    (0x00, 0x00, 0x00), (0x00, 0x00, 0x00),
)

ROOT = Path(__file__).resolve().parents[1]
RGB_INCLUDE = ROOT / "codegen" / "lib" / "nes_palette_rgb.inc"
NEOGEO_INCLUDE = (
    ROOT / "platform" / "neogeo" / "nes_palette_neogeo.inc"
)


class PaletteError(ValueError):
    """The canonical palette or a generated include is invalid."""


def rgb8_palette() -> tuple[tuple[int, int, int], ...]:
    if len(FCEUX_221_RGB6) != 64:
        raise PaletteError(
            f"expected 64 palette entries, found {len(FCEUX_221_RGB6)}"
        )
    if any(
        not 0 <= component <= 0x3F
        for color in FCEUX_221_RGB6
        for component in color
    ):
        raise PaletteError("six-bit palette component is out of range")
    return tuple(
        tuple(component << 2 for component in color)
        for color in FCEUX_221_RGB6
    )


def decode_neogeo_color(word: int) -> tuple[int, int, int]:
    """Decode the Neo Geo's five per-channel bits plus shared low bit."""

    shared_low = ((word >> 15) & 1) ^ 1
    red5 = (((word >> 8) & 0x0F) << 1) | ((word >> 14) & 1)
    green5 = (((word >> 4) & 0x0F) << 1) | ((word >> 13) & 1)
    blue5 = ((word & 0x0F) << 1) | ((word >> 12) & 1)
    return tuple(
        ((component << 1) | shared_low) << 2
        for component in (red5, green5, blue5)
    )


def _nearest_component(value: int, shared_low: int) -> int:
    return min(
        range(32),
        key=lambda component: (
            abs(value - ((component * 8) + (shared_low * 4))),
            component,
        ),
    )


def encode_neogeo_color(rgb: tuple[int, int, int]) -> int:
    """Choose the deterministic nearest representable Neo Geo color."""

    candidates: list[tuple[tuple[int, int, int], int]] = []
    for shared_low in (0, 1):
        red5, green5, blue5 = (
            _nearest_component(value, shared_low) for value in rgb
        )
        word = (
            ((shared_low ^ 1) << 15)
            | ((red5 & 1) << 14)
            | ((green5 & 1) << 13)
            | ((blue5 & 1) << 12)
            | ((red5 >> 1) << 8)
            | ((green5 >> 1) << 4)
            | (blue5 >> 1)
        )
        decoded = decode_neogeo_color(word)
        errors = tuple(abs(source - target) for source, target in zip(rgb, decoded))
        key = (sum(error * error for error in errors), max(errors), word)
        candidates.append((key, word))
    return min(candidates)[1]


def neogeo_palette() -> tuple[int, ...]:
    return tuple(encode_neogeo_color(color) for color in rgb8_palette())


def _header() -> str:
    return (
        "/* Generated by tools/gen_neogeo_palette.py. Do not edit.\n"
        f" * Source profile: {PALETTE_NAME}\n"
        " * Provenance: THIRD_PARTY_NOTICES.md\n"
        " */\n"
    )


def render_rgb_include() -> str:
    values = [
        component
        for color in rgb8_palette()
        for component in color
    ]
    lines = [
        "    " + ", ".join(f"0x{value:02x}" for value in values[index:index + 12]) + ","
        for index in range(0, len(values), 12)
    ]
    return _header() + "\n".join(lines) + "\n"


def render_neogeo_include() -> str:
    words = neogeo_palette()
    lines = [
        "    " + ", ".join(f"0x{word:04x}u" for word in words[index:index + 8]) + ","
        for index in range(0, len(words), 8)
    ]
    return _header() + "\n".join(lines) + "\n"


def generated_outputs() -> tuple[tuple[Path, str], ...]:
    return (
        (RGB_INCLUDE, render_rgb_include()),
        (NEOGEO_INCLUDE, render_neogeo_include()),
    )


def write_generated() -> None:
    for path, content in generated_outputs():
        path.write_text(content, encoding="ascii")


def check_generated() -> None:
    stale: list[str] = []
    for path, expected in generated_outputs():
        if not path.is_file() or path.read_text(encoding="ascii") != expected:
            stale.append(str(path.relative_to(ROOT)))
    if stale:
        raise PaletteError(
            "stale generated palette include(s): "
            + ", ".join(stale)
            + "; run python3 tools/gen_neogeo_palette.py --write"
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="rewrite both tracked generated includes instead of checking them",
    )
    return parser.parse_args()


def main() -> int:
    arguments = parse_args()
    try:
        if arguments.write:
            write_generated()
            print("Generated desktop and Neo Geo palette includes")
        else:
            check_generated()
            print(f"Generated palette includes: OK ({PALETTE_NAME})")
        return 0
    except (OSError, PaletteError) as error:
        print(f"palette generation failed: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
